apiVersion: v1
kind: Service
metadata:
  name: ai-monitoring-agent
  namespace: jupiter
  labels:
    app: ai-monitoring-agent
spec:
  selector:
    app: ai-monitoring-agent
  ports:
    - name: dashboard
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: ollama
      protocol: TCP
      port: 11434
      targetPort: 11434
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
  type: ClusterIP
