apiVersion: v1
kind: Service
metadata:
  name: ai-monitoring-agent
  namespace: mercury
  labels:
    app: ai-monitoring-agent-otel-relay
spec:
  type: ExternalName
  externalName: ai-monitoring-agent.jupiter.svc.cluster.local
  ports:
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
